name: Compile and release (PC)

# Tradução: quando houver uma atualização (push) ou pedido de atualização (pull request) nos arquivos hane_pc.txt, este script poderá ser rodado, mas APENAS se houver a adição de uma tag
on:
  push:
    tags:
    - '*'
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: compile patch
      run: python dependencies\compile_pc.py

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: HE.KT.Umineko.Hane.PT-BR.(Legacy.Art).7z   # nome do arquivo final que irá para os releases
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
